const funFacts = [
    "The Mets were founded in 1962 to replace the departed Dodgers and Giants.",
    "Mr. Met was the first MLB mascot to appear in human form.",
    "Tom Seaver was nicknamed 'The Franchise'.",
    "David Wright’s nickname was 'Captain America'.",
    "The Mets' first World Series win was in 1969 — the Miracle Mets!",
    "Dwight Gooden threw a no-hitter in 1996.",
    "The Mets' longest game ever lasted 24 innings.",
    "Mike Piazza hit the first home run in NYC after 9/11.",
    "Mets fans once booed Santa Claus (just like Philly fans!).",
    "The Mets' original colors are a blend of the Dodgers (blue) and Giants (orange).",
    // Add more up to 75:
    "The Mets play at Citi Field, which opened in 2009.",
    "Bartolo Colon hit his first and only home run at age 42.",
    "The Mets once traded Nolan Ryan before he became a legend.",
    "In 1986, the Mets had 108 regular-season wins.",
    "Keith Hernandez appeared on *Seinfeld* as himself.",
    "Mets pitcher Johan Santana threw the team's first no-hitter in 2012.",
    "In 2015, the Mets went to the World Series with an electric young rotation.",
    "Jacob deGrom won Rookie of the Year in 2014.",
    "Pete Alonso hit 53 home runs in his rookie season — an MLB record.",
    "The Mets have a tradition of playing the song 'Piano Man' after games.",
    "Francisco Lindor was traded to the Mets in 2021.",
    "The Mets once wore racing stripes on their uniforms.",
    "In 2000, the Mets faced the Yankees in the 'Subway Series' World Series.",
    "Gary, Keith, and Ron are a legendary TV booth trio.",
    "Dwight Gooden was only 19 when he debuted.",
    "The 1986 team was known for being talented... and rowdy.",
    "The Mets bullpen cart in the '80s had a baseball cap on top.",
    "In 1973, Tug McGraw coined the phrase 'Ya Gotta Believe!'",
    "R.A. Dickey won a Cy Young Award with a knuckleball in 2012.",
    "Mookie Wilson’s ground ball helped win Game 6 of the 1986 World Series.",
    "Darryl Strawberry hit 252 home runs with the Mets.",
    "Doc Gooden won the Triple Crown of pitching in 1985.",
    "The Mets once had the highest payroll in MLB.",
    "Bobby Bonilla still gets paid by the Mets every July 1st!",
    "Citi Field has an apple that pops up after every Mets home run.",
    "In 2022, the Mets threw a combined no-hitter against the Phillies.",
    "Jose Reyes led the league in triples four times.",
    "The Mets' mascot Mr. Met once flipped off a fan (and went viral!).",
    "Nimmo is known for sprinting to first on a walk.",
    "Steve Cohen bought the Mets in 2020.",
    "Keith Hernandez is known for his epic mustache.",
    "Buck Showalter managed the Mets in 2022 and 2023.",
    "The Mets were the first team to wear black jerseys in the '90s.",
    "Jacob deGrom once hit a home run and struck out 13 in the same game.",
    "The Mets’ minor league team is the Syracuse Mets.",
    "In 2022, Edwin Díaz’s entrance to 'Narco' became iconic.",
    "The Mets were almost called the 'Meadowlarks' or 'Skyliners'.",
    "Tim Tebow once played for the Mets minor leagues.",
    "The 1986 parade had over 2 million people.",
    "David Wright holds the team record for hits.",
    "The Mets have had multiple walk-off wins on Opening Day.",
    "Yogi Berra once managed the Mets.",
    "Noah Syndergaard’s nickname is 'Thor'.",
    "Bartolo Colon’s home run is one of baseball’s most meme-worthy moments.",
    "The Mets once had a stadium proposal rejected due to budget.",
    "Citi Field has Shake Shack, one of the best ballpark eats.",
    "In 2023, the Mets played a game in London.",
    "Max Scherzer joined the Mets with a record-breaking contract.",
    "Steve Cohen is the richest owner in MLB.",
    "The Mets celebrated their 60th anniversary in 2022.",
    "Daisuke Matsuzaka had a short stint with the Mets.",
    "In 1986, Bill Buckner’s error led to a Mets win in Game 6.",
    "The Mets once traded Scott Kazmir and regretted it badly.",
    "Yoenis Céspedes helped lead the 2015 playoff run.",
    "Carlos Beltrán once struck out looking to end the NLCS.",
    "Tom Seaver returned to the Mets in 1983.",
    "The Mets retired Mike Piazza's #31 in 2016.",
    "The Mets have had multiple players win Gold Gloves.",
    "They’ve had two managers named Terry (Collins and Pendleton).",
    "Some fans wear horse masks for good luck at Citi Field.",
    "Mets fans have their own subreddit called r/letsgoMets.",
    "The Mets’ AAA affiliate used to be in Las Vegas.",
    "The Mets were featured on a '30 for 30' documentary.",
    "Their 2015 run had a viral chant: 'We Took Back New York!'"
  ];

  const randomIndex = Math.floor(Math.random() * funFacts.length);
  document.getElementById('mets-funfact').textContent = funFacts[randomIndex] ;



  